### ISSUE TITLE
[Deps] Bump json-schema-validator

### ISSUE THREAD

**Issue by squakez** [syndesisio/syndesis#8628]
Failed in #8602 with:

```
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.syndesis.extension.converter.ExtensionSchemaValidationTest
[ERROR] Tests run: 4, Failures: 0, Errors: 3, Skipped: 1, Time elapsed: 0.701 s <<< FAILURE! - in io.syndesis.extension.converter.ExtensionSchemaValidationTest
[ERROR] validateStepExtensionTest(io.syndesis.extension.converter.ExtensionSchemaValidationTest)  Time elapsed: 0.636 s  <<< ERROR!
java.lang.NoSuchMethodError: com.github.fge.jackson.JsonNumEquals.getInstance()Lcom/google/common/base/Equivalence;
	at io.syndesis.extension.converter.ExtensionSchemaValidationTest.validateStepExtensionTest(ExtensionSchemaValidationTest.java:63)
[ERROR] upgradePublicModelExtensionTest(io.syndesis.extension.converter.ExtensionSchemaValidationTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.github.fge.jsonschema.cfg.ValidationConfigurationBuilder
	at io.syndesis.extension.converter.ExtensionSchemaValidationTest.upgradePublicModelExtensionTest(ExtensionSchemaValidationTest.java:95)
[ERROR] addSchemaVersionInPublicModelExtensionTest(io.syndesis.extension.converter.ExtensionSchemaValidationTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class com.github.fge.jsonschema.cfg.ValidationConfigurationBuilder
	at io.syndesis.extension.converter.ExtensionSchemaValidationTest.addSchemaVersionInPublicModelExtensionTest(ExtensionSchemaValidationTest.java:119)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   ExtensionSchemaValidationTest.addSchemaVersionInPublicModelExtensionTest:119 » NoClassDefFound
[ERROR]   ExtensionSchemaValidationTest.upgradePublicModelExtensionTest:95 » NoClassDefFound
[ERROR]   ExtensionSchemaValidationTest.validateStepExtensionTest:63 » NoSuchMethod com....
[INFO] 
[ERROR] Tests run: 4, Failures: 0, Errors: 3, Skipped: 1
```
