### PR TITLE
fix: Missing patch body in FHIR Patch operation

### PR DESCRIPTION
**Pull request by rkorytkowski**
ENTESB-14237

(cherry picked from commit 59067f35053c26d99d65b4d76e2d3194d5b64e3a)

### CODE REVIEW

**Comment by mkralik3** [comment]
@rkorytkowski Hi, unfortunetelly our infrastructure isn't working so the QE smoke tests was not triggered. I have manually downloaded images from GitHub actions, run the Syndesis on our cluster and run smoke test which passed. Also, I have run two reproducers for ENTESB-15445 and both passed. So we can merge this PR.

**Comment by zregvart** [comment]
@rkorytkowski this needs to be fixed to work with JUnit 5, it doesn't compile on 1.12.x:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project connector-fhir: Compilation failure: Compilation failure: 
Error:  /home/runner/work/syndesis/syndesis/app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirPatchWithBodyTest.java:[21,17] cannot find symbol
Error:    symbol:   class Test
Error:    location: package org.junit
Error:  /home/runner/work/syndesis/syndesis/app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirPatchWithBodyAndPropertiesTest.java:[21,17] cannot find symbol
Error:    symbol:   class Test
Error:    location: package org.junit
Error:  /home/runner/work/syndesis/syndesis/app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirPatchWithBodyTest.java:[42,6] cannot find symbol
Error:    symbol:   class Test
Error:    location: class io.syndesis.connector.fhir.FhirPatchWithBodyTest
Error:  /home/runner/work/syndesis/syndesis/app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirPatchWithBodyTest.java:[50,6] cannot find symbol
Error:    symbol:   class Test
Error:    location: class io.syndesis.connector.fhir.FhirPatchWithBodyTest
Error:  /home/runner/work/syndesis/syndesis/app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirPatchWithBodyAndPropertiesTest.java:[43,6] cannot find symbol
Error:    symbol:   class Test
Error:    location: class io.syndesis.connector.fhir.FhirPatchWithBodyAndPropertiesTest
Error:  /home/runner/work/syndesis/syndesis/app/connector/fhir/src/test/java/io/syndesis/connector/fhir/FhirPatchWithBodyAndPropertiesTest.java:[51,6] cannot find symbol
Error:    symbol:   class Test
Error:    location: class io.syndesis.connector.fhir.FhirPatchWithBodyAndPropertiesTest
Error:  -> [Help 1]
```

**Comment by Delawen** [comment]
Right, I did the testing without pulling first :/

**Comment by Delawen** [comment]
@rkorytkowski 

Most of the changes are easy:
```
-import org.junit.Test;
+import org.junit.jupiter.api.Test;
```
and
```
-template.
+template()
```

**Comment by zregvart** [comment]
I can create a quick PR to fix this...

**Comment by zregvart** [comment]
In https://github.com/syndesisio/syndesis/pull/9500
